server:
  port: 8082

spring:
  application:
    name: payment-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

 instance:
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
