server:
  port: 8082

spring:
  application:
    name: payment-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.40
    health-check-url:     http://192.168.1.40:8082/actuator/health
    status-page-url:      http://192.168.1.40:8082/actuator/info
    home-page-url:        http://192.168.1.40:8082/health

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
